baseurl         = "/"
languageCode    = "pt-br"
title           = "s2<3"
theme           = "hugo-webslides"

[params]
  author = "Tiago"
  homepage = "tiagodalloca.github.io"

[params.webslides]
  banner = false
  slideshow = true
  vertical = false
  autoslide = false
  changeOnClick = false
  disableLoop = false
  minWheelDelta = 40
  disableNavigateOnScroll = false
  scrollWait = 450
  slideOffset = 50
  hideIndex = false


[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingID = true
      autoHeadingIDType = 'blackfriday'
      wrapStandAloneImageWithinParagraph = true
    [markup.goldmark.renderer]
      unsafe = true
