## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Mult - móvel modular"
theme = "hugo-story"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"


## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "O móvel modular que você não sabia que sua casa precisava"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/tiagodalloca/tiagodalloca.github.io/blob/master/subsites/leroy-merlin-showcase"
  email = "tdalloca@gmail.com"

